version: "3.6"
services:
  run-visualizer:
    build:
      network: host
      context: .
    ports:
      - "8081:80"
    restart: always
    environment:
      - NODE_GRAPHQL_ENDPOINT
      - NODE_MAX_LOGS
      - NODE_MAX_SWEEPS
